[package]
name = "c122_albatros_rustico"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
sha1 = "0.10.1"
native-tls = "0.2.10"
gtk = "0.15.5"
gio = "0.15.1"
glib = "0.15.5"