name: CI

# Specify when this workflow will run
on:
  push: # Run when pushing...
    branches: [main] # to main branch.
  pull_request: # Run when creating a Pull Request...
    branches: [main] # against main branch.

defaults:
  run:
    # This can be used to specify a custom
    # working-directory to your root cargo project
    #
    # Example:
    # working-directory: ./my-cargo-project
    working-directory: ./

env:
  # Prettify cargo output
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install GTK
        run: sudo apt-get install -y libgtk-3-dev
      - name: Run format check client
        run: cargo fmt --check
        working-directory: bittorrent_client
      - name: Run check client
        run: cargo check --color always
        working-directory: bittorrent_client
      - name: Run clippy client
        run: cargo clippy --color always -- -D warnings
        working-directory: bittorrent_client
      - name: Run format check tracker
        run: cargo fmt --check
        working-directory: bittorrent_tracker
      - name: Run check tracker
        run: cargo check --color always
        working-directory: bittorrent_tracker
      - name: Run clippy tracker
        run: cargo clippy --color always -- -D warnings
        working-directory: bittorrent_tracker

  test:
    needs: [lint] # Run after lint has successfully passed
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install GTK
        run: sudo apt-get install -y libgtk-3-dev
      - name: Run tests client

        run: cargo test
        working-directory: bittorrent_client
      - name: Run tests tracker
        run: cargo test
        working-directory: bittorrent_tracker